version: 2
updates:
  # Rust (Cargo)
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: quarterly

  # NPM
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: quarterly

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: quarterly
