name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking changes"
    labels:
      - "breaking"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐞 Bug fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧰 Maintenance"
    label:
      - "chore"
  - title: "🔧 Dependency updates"
    labels:
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
exclude-labels:
  - "skip-changelog"
exclude-contributors:
  - "MalpenZibo"
  - "dependabot"
  - "dependabot[bot]"
no-contributors-template: "just me this time 😅"
autolabeler:
  - label: "docs"
    branch:
      - '/^docs\/.+/'
    title:
      - "/^docs/i"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - "/feature/i"
      - '/feat\/.+/'
  - label: "chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"
  - label: "dependencies"
    branch:
      - '/dependabot\/.+/'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  ❤️ A big thanks to $CONTRIBUTORS
