[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/MalpenZibo/iced"]
git = "https://github.com/MalpenZibo/iced"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/cosmic-protocols?rev=178eb0b"]
git = "https://github.com/pop-os/cosmic-protocols"
rev = "178eb0b"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/cosmic-text.git"]
git = "https://github.com/pop-os/cosmic-text.git"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/glyphon.git?tag=iced-0.14-dev"]
git = "https://github.com/pop-os/glyphon.git"
tag = "iced-0.14-dev"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/smithay-clipboard?tag=pop-dnd-5"]
git = "https://github.com/pop-os/smithay-clipboard"
tag = "pop-dnd-5"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/softbuffer?tag=cosmic-4.0"]
git = "https://github.com/pop-os/softbuffer"
tag = "cosmic-4.0"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/window_clipboard.git?tag=pop-0.13-2"]
git = "https://github.com/pop-os/window_clipboard.git"
tag = "pop-0.13-2"
replace-with = "vendored-sources"

[source."git+https://github.com/pop-os/winit.git?tag=iced-xdg-surface-0.13"]
git = "https://github.com/pop-os/winit.git"
tag = "iced-xdg-surface-0.13"
replace-with = "vendored-sources"

[source."git+https://github.com/wash2/accesskit?tag=iced-xdg-surface-0.13"]
git = "https://github.com/wash2/accesskit"
tag = "iced-xdg-surface-0.13"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
