use iced::{
    Font,
    widget::{Text, text},
};

#[derive(Copy, Clone, Default)]
pub enum Icons {
    #[default]
    None,
    AppLauncher,
    Clipboard,
    Refresh,
    NoUpdatesAvailable,
    UpdatesAvailable,
    MenuClosed,
    MenuOpen,
    Cpu,
    Mem,
    Temp,
    Speaker0,
    Speaker1,
    Speaker2,
    Speaker3,
    Headphones0,
    Headphones1,
    Headset,
    Mic0,
    Mic1,
    MonitorSpeaker,
    ScreenShare,
    Battery0,
    Battery1,
    Battery2,
    Battery3,
    Battery4,
    BatteryCharging,
    Wifi0,
    Wifi1,
    Wifi2,
    Wifi3,
    Wifi4,
    Wifi5,
    WifiLock1,
    WifiLock2,
    WifiLock3,
    WifiLock4,
    WifiLock5,
    Ethernet,
    Vpn,
    Bluetooth,
    PowerSaver,
    Balanced,
    Performance,
    EyeOpened,
    EyeClosed,
    Lock,
    Power,
    Reboot,
    Suspend,
    Logout,
    RightArrow,
    Brightness,
    Point,
    Close,
    Airplane,
    Webcam,
    SkipPrevious,
    Play,
    Pause,
    SkipNext,
    MusicNote,
    Drive,
    IpAddress,
    DownloadSpeed,
    UploadSpeed,
    Copy,
    RightChevron,
    Keyboard,
    Mouse,
    Test,
}

impl From<Icons> for &'static str {
    fn from(icon: Icons) -> &'static str {
        match icon {
            Icons::None => "",
            Icons::AppLauncher => "\u{f003b}",
            Icons::Clipboard => "\u{f014c}",
            Icons::Refresh => "\u{f0453}",
            Icons::NoUpdatesAvailable => "\u{f05e0}",
            Icons::UpdatesAvailable => "\u{f0cdb}",
            Icons::MenuClosed => "\u{f035f}",
            Icons::MenuOpen => "\u{f035d}",
            Icons::Cpu => "\u{f0502}",
            Icons::Mem => "\u{efc5}",
            Icons::Temp => "\u{f050f}",
            Icons::Speaker0 => "\u{f0e08}",
            Icons::Speaker1 => "\u{f057f}",
            Icons::Speaker2 => "\u{f0580}",
            Icons::Speaker3 => "\u{f057e}",
            Icons::Headphones0 => "\u{f07ce}",
            Icons::Headphones1 => "\u{f02cb}",
            Icons::Headset => "\u{f02ce}",
            Icons::Mic0 => "\u{f036d}",
            Icons::Mic1 => "\u{f036c}",
            Icons::ScreenShare => "\u{f1483}",
            Icons::MonitorSpeaker => "\u{f0f5f}",
            Icons::Battery0 => "\u{f0083}",
            Icons::Battery1 => "\u{f007c}",
            Icons::Battery2 => "\u{f007e}",
            Icons::Battery3 => "\u{f0080}",
            Icons::Battery4 => "\u{f0079}",
            Icons::BatteryCharging => "\u{f0084}",
            Icons::Wifi0 => "\u{f092d}",
            Icons::Wifi1 => "\u{f092f}",
            Icons::Wifi2 => "\u{f091f}",
            Icons::Wifi3 => "\u{f0922}",
            Icons::Wifi4 => "\u{f0925}",
            Icons::Wifi5 => "\u{f0928}",
            Icons::WifiLock1 => "\u{f092c}",
            Icons::WifiLock2 => "\u{f0921}",
            Icons::WifiLock3 => "\u{f0924}",
            Icons::WifiLock4 => "\u{f0927}",
            Icons::WifiLock5 => "\u{f092a}",
            Icons::Ethernet => "\u{f0200}",
            Icons::Vpn => "\u{f0582}",
            Icons::Bluetooth => "\u{f00af}",
            Icons::PowerSaver => "\u{f0f86}",
            Icons::Balanced => "\u{f0f85}",
            Icons::Performance => "\u{f04c5}",
            Icons::EyeOpened => "\u{f0208}",
            Icons::EyeClosed => "\u{f0209}",
            Icons::Lock => "\u{f033e}",
            Icons::Power => "\u{f0425}",
            Icons::Reboot => "\u{f0450}",
            Icons::Suspend => "\u{f0904}",
            Icons::Logout => "\u{f05fd}",
            Icons::RightArrow => "\u{f0054}",
            Icons::Brightness => "\u{f00e0}",
            Icons::Point => "\u{f444}",
            Icons::Close => "\u{f0156}",
            Icons::Airplane => "\u{f001d}",
            Icons::Webcam => "\u{f03d}",
            Icons::SkipPrevious => "\u{f04ae}",
            Icons::Play => "\u{f040a}",
            Icons::Pause => "\u{f03e4}",
            Icons::SkipNext => "\u{f04ad}",
            Icons::MusicNote => "\u{f0387}",
            Icons::Drive => "\u{f02ca}",
            Icons::IpAddress => "\u{f0a60}",
            Icons::DownloadSpeed => "\u{f06f4}",
            Icons::UploadSpeed => "\u{f06f6}",
            Icons::Copy => "\u{f018f}",
            Icons::RightChevron => "\u{f0142}",
            Icons::Keyboard => "\u{f030c}",
            Icons::Mouse => "\u{f037d}",
            Icons::Test => "\u{c0000}",
        }
    }
}

pub fn icon<'a>(r#type: Icons) -> Text<'a> {
    text(std::convert::Into::<&'static str>::into(r#type)).font(Font::with_name("Ashell Nerd Font"))
}

pub fn icon_raw<'a>(s: String) -> Text<'a> {
    text(s).font(Font::with_name("Ashell Nerd Font"))
}
