use iced::{
    Font,
    widget::{Text, text},
};

#[derive(Copy, Clone, Default)]
pub enum Icons {
    #[default]
    None,
    AppLauncher,
    Clipboard,
    Refresh,
    NoUpdatesAvailable,
    UpdatesAvailable,
    MenuClosed,
    MenuOpen,
    Cpu,
    Mem,
    Temp,
    Speaker0,
    Speaker1,
    Speaker2,
    Speaker3,
    Headphones0,
    Headphones1,
    Headset,
    Mic0,
    Mic1,
    MonitorSpeaker,
    ScreenShare,
    Battery0,
    Battery1,
    Battery2,
    Battery3,
    Battery4,
    BatteryCharging,
    Wifi0,
    Wifi1,
    Wifi2,
    Wifi3,
    Wifi4,
    Wifi5,
    WifiLock1,
    WifiLock2,
    WifiLock3,
    WifiLock4,
    WifiLock5,
    Ethernet,
    Vpn,
    Bluetooth,
    PowerSaver,
    Balanced,
    Performance,
    EyeOpened,
    EyeClosed,
    Lock,
    Power,
    Reboot,
    Suspend,
    Logout,
    RightArrow,
    Brightness,
    Point,
    Close,
    VerticalDots,
    Airplane,
    Webcam,
    SkipPrevious,
    PlayPause,
    SkipNext,
    MusicNote,
}

impl From<Icons> for &'static str {
    fn from(icon: Icons) -> &'static str {
        match icon {
            Icons::None => "",
            Icons::AppLauncher => "󱗼",
            Icons::Clipboard => "󰅌",
            Icons::Refresh => "󰑐",
            Icons::NoUpdatesAvailable => "󰗠",
            Icons::UpdatesAvailable => "󰳛",
            Icons::MenuClosed => "",
            Icons::MenuOpen => "",
            Icons::Cpu => "󰔂",
            Icons::Mem => "󰘚",
            Icons::Temp => "󰔏",
            Icons::Speaker0 => "󰸈",
            Icons::Speaker1 => "󰕿",
            Icons::Speaker2 => "󰖀",
            Icons::Speaker3 => "󰕾",
            Icons::Headphones0 => "󰟎",
            Icons::Headphones1 => "󰋋",
            Icons::Headset => "󰋎",
            Icons::Mic0 => "󰍭",
            Icons::Mic1 => "󰍬",
            Icons::ScreenShare => "󱒃",
            Icons::MonitorSpeaker => "󰽟",
            Icons::Battery0 => "󰂃",
            Icons::Battery1 => "󰁼",
            Icons::Battery2 => "󰁾",
            Icons::Battery3 => "󰂀",
            Icons::Battery4 => "󰁹",
            Icons::BatteryCharging => "󰂄",
            Icons::Wifi0 => "󰤭",
            Icons::Wifi1 => "󰤯",
            Icons::Wifi2 => "󰤟",
            Icons::Wifi3 => "󰤢",
            Icons::Wifi4 => "󰤥",
            Icons::Wifi5 => "󰤨",
            Icons::WifiLock1 => "󰤬",
            Icons::WifiLock2 => "󰤡",
            Icons::WifiLock3 => "󰤤",
            Icons::WifiLock4 => "󰤧",
            Icons::WifiLock5 => "󰤪",
            Icons::Ethernet => "󰈀",
            Icons::Vpn => "󰖂",
            Icons::Bluetooth => "󰂯",
            Icons::PowerSaver => "󰾆",
            Icons::Balanced => "󰾅",
            Icons::Performance => "󰓅",
            Icons::EyeOpened => "󰈈",
            Icons::EyeClosed => "󰈉",
            Icons::Lock => "󰌾",
            Icons::Power => "󰐥",
            Icons::Reboot => "󰑐",
            Icons::Suspend => "󰤄",
            Icons::Logout => "󰗽",
            Icons::RightArrow => "󰁔",
            Icons::Brightness => "󰃠",
            Icons::Point => "",
            Icons::Close => "󰅖",
            Icons::VerticalDots => "󰇙",
            Icons::Airplane => "󰀝",
            Icons::Webcam => "",
            Icons::SkipPrevious => "󰒮",
            Icons::PlayPause => "󰐎",
            Icons::SkipNext => "󰒭",
            Icons::MusicNote => "󰎇",
        }
    }
}

pub fn icon<'a>(r#type: Icons) -> Text<'a> {
    text(std::convert::Into::<&'static str>::into(r#type))
        .font(Font::with_name("Symbols Nerd Font"))
}

pub fn icon_raw<'a>(s: String) -> Text<'a> {
    text(s).font(Font::with_name("Symbols Nerd Font"))
}
