name: Nix CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  checks-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - 'assets/**'
              - 'build.rs'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/nix-ci.yml'

      - uses: nixbuild/nix-quick-install-action@v34
        if: steps.filter.outputs.code == 'true'

      - name: Restore and save Nix store
        if: steps.filter.outputs.code == 'true'
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than 0 seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never
          # collect garbage until Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 3 GB = 3221225472 B
          gc-max-store-size-linux: 3221225472

      - name: Nix build
        if: steps.filter.outputs.code == 'true'
        run: nix build
