name: Draft Release
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read

jobs:
  update-release-draft:
    if: github.event_name == 'push'
    name: Update release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-pr:
    if: github.event_name == 'pull_request_target'
    name: Label PR
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
